# Numpy Random package (deadline: 22/11/2021)
## What is it?
***


**"Numpy** is a python library that provides multidimensional array object, for fast operations on arrays."; "contains multidimensional array and matrix data structures"; "It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices "
**Random package** produces pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions. *[reference]*

PCG64 vs M19937T: Better statistical properties and faster

## Simple Random Data 

In [14]:
import numpy as np
rng = np.random.default_rng()
rfloat = rng.random(size=3) # generate 3 random float numbers
rint = rng.integers(100, size=3) #generate 3 random integers
rint

array([40, 31, 36], dtype=int64)

## What is Seeding
Seeding is to make sure same sets of Psuedo random number is generated for easier replication of output. if you provide the same seed, you will get the same output.And if you change the seed, you will get a different output. The output that you get depends on the input that you give it.<br/>

**How to Seed?**

In [1]:
import numpy as np
np.random.seed(1)
np.random.random() # generate a random float number between 0 and 1

0.417022004702574

In [5]:
np.random.seed(2)
# generate 10 random float numbers between 0 and 1
np.random.random(size = 10) 

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728])

In [6]:
np.random.seed(3)
# generate 10 random integer between 0 (inclusive) and 100 (exclusive)
np.random.randint(low=0, high=100, size = 10)

array([24,  3, 56, 72,  0, 21, 19, 74, 41, 10])

In [8]:
np.random.seed(4)
# generate 10 random integer between 0 (inclusive) and 100 (exclusive)
np.random.randint(100, size = 10) # different seed different output

array([46, 55, 69,  1, 87, 72, 50,  9, 58, 94])

It works with other functions in random package, eg: numpy.random.normal to create normally distributed numbers or numpy.random.choice to generate a random sample from an input

Optional axis argument for methods like choice, permutation and shuffle that controls which axis an operation is performed over for multi-dimensional arrays.

 ## Permutation function
 ** why?**
 There are 3 methods of permutations, shuffle, permutation and permuted

#### Shuffle(x,[,axis])
in-place, order of sub-arrays is changed, but contents remains the same, works on 1-d, 2-d arrays

#### permutation(x[,axis])
make a copy, shuffle elements in the array randomly

#### permuted(x[,axis, out])
if out is given, shuffled array is returned there; if out is none, a shuffled copy is returned 

## explain the use and purpose of 5 distributions